export const sampleRestaurants = [
  {
    restaurant_id: 1,
    restaurant_name: 'La Trattoria',
    rating: 4,
    city: 'Rome',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
  },
  {
    restaurant_id: 2,
    restaurant_name: 'Osteria del Corso',
    rating: 1,
    city: 'Florence',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg',
  },
  {
    restaurant_id: 3,
    restaurant_name: 'Ristorante Napoli',
    rating: 0,
    city: 'Naples',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg',
  },
  {
    restaurant_id: 4,
    restaurant_name: 'Venezia Cucina',
    rating: 2,
    city: 'Venice',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
  },
  {
    restaurant_id: 5,
    restaurant_name: 'Milano Bites',
    rating: 4,
    city: 'Milan',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg',
  },
  {
    restaurant_id: 6,
    restaurant_name: 'Bologna Bistro',
    rating: 3,
    city: 'Bologna',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg',
  },
  {
    restaurant_id: 7,
    restaurant_name: 'Sicilian Flavors',
    rating: 4,
    city: 'Palermo',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg',
  },
  {
    restaurant_id: 8,
    restaurant_name: 'Pisa Plates',
    rating: 2,
    city: 'Pisa',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/Sintel.jpg',
  },
  {
    restaurant_id: 9,
    restaurant_name: 'Turin Taste',
    rating: 1,
    city: 'Turin',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/SubaruOutbackOnStreetAndDirt.jpg',
  },
  {
    restaurant_id: 10,
    restaurant_name: 'Genoa Gourmet',
    rating: 0,
    city: 'Genoa',
    img: 'https://storage.googleapis.com/gtv-videos-bucket/sample/images/TearsOfSteel.jpg',
  },
];